<a href="https://colab.research.google.com/github/Jhansipothabattula/Machine_Learning/blob/main/Day08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Advanced Linear Algebra concepts

**Determinants and Inverse of a Matrix**
1. Determinants
   
- Scalar value that provides information about a matrix's properties
- Only for square matrices
- det(A) = 0, the matrix A is singular
- det(A)! = 0, A is invertible
- Geometric interpretation
- for a 2x2 matrix , the determinant represents the scaling factor of the area formed by it's column vectors
- Formula for 2x2 matrix:
$$
\det \begin{pmatrix}
a & b \\
c & d
\end{pmatrix}
= ad - bc
$$

    


           
       


**Determinants and Inverse of a matrix**
1. Inverse of a Matrix

- Denoted as $A^{-1}$

- Product of a Matrix and it's inverse is the identity matrix: Ax$A^{-1}$
- Matrix is invertible only if det(A)!=0
- Formula for 2x2 2x2 Matrix
$$
A^{-1} = \frac{1}{\det(A)}
\begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix}
$$

$$
A^{-1} = \frac{1}{ad - bc}
\begin{pmatrix}
d & -b \\
-c & a
\end{pmatrix}
$$

In [ ]:
import numpy as np
A = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(A)
print("Determinant: \n", determinant)
inverse = np.linalg.inv(A)
print("Inverse: \n", inverse)

Determinant: 
 5.000000000000001
Inverse: 
 [[ 0.8 -0.6]
 [-0.2  0.4]]


**Eigenvalues and Eigenvectors**

- *What are Eigenvalues and Eigenvectors?*
- If A . V = $\lambda$
 . V, then

  - V is an Eigenvector

  - $\lambda$ is the Eigenvalue

- *Geometric Interpretation*
   
   - Eigenvectors point in the direction where the matrix transformation stretches or compresses vectors
   - Eigenvalues indicate the factor of stretching or compression

- *Properties*
   
   - Matrix of size nxn has n Eigenvalues and Eigenvectors
   - Eigenvalues can be real or complex
   - For a symmetric matrix, Eigenvalues are always real

- *Computing Eigenvalues and Eigenvectors in Numpy*



In [ ]:
import numpy as np
A = np.array([[1, 2], [1, 4]])
determinant = np.linalg.det(A)
print("Determinant: \n", determinant)
inverse = np.linalg.inv(A)
print("Inverse: \n", inverse)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues: \n", eigenvalues)
print("Eigenvectors: \n", eigenvectors)
B = np.array([[4, 2], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(B)
print("Eigenvalues: \n", eigenvalues)
print("Eigenvectors: \n", eigenvectors)

Determinant: 
 2.0
Inverse: 
 [[ 2.  -1. ]
 [-0.5  0.5]]
Eigenvalues: 
 [0.43844719 4.56155281]
Eigenvectors: 
 [[-0.96276969 -0.48963374]
 [ 0.27032301 -0.87192821]]
Eigenvalues: 
 [4.56155281 0.43844719]
Eigenvectors: 
 [[ 0.96276969 -0.48963374]
 [ 0.27032301  0.87192821]]


**Introduction to Matrix Decomposition**

- What is Matrix Decomposition?

  - Process of breaking a Matrix into simpler components to analyze or solve problems

- singular Value Decomposition(SVD)

  - SVD decomposes a Mtrix A into three Matrices: A = U . $\sum$ . $v^{-1}$
   
     - U: Left Singular Vectors(Orthogonal matrix)

     - $\sum$: Diagonal Matrix of Singular values(non-Negative)
   
     - $v^{-1}$: Right Singular Vectors(Orthogonal Matrix)
   - Eigenvalues indicate the factor of stretching or compression

- Applications of SVD
   - Dimensionality reduction (PCA)

  - Image compression

  - Noise removal

  - Pseudoinverse computation

  - Solving linear systems

  - Recommender systems

  - Latent semantic analysis in NLP.
   
   - Matrix of size nxn has n Eigenvalues and Eigenvectors
   - Eigenvalues can be real or complex
   - For a symmetric matrix, Eigenvalues are always real

- Computing SVD in Numpy



In [ ]:
import numpy as np
U, S, Vt = np.linalg.svd(A)
print("U: \n", U)
print("Singular Values: \n", S)
print("V Transpose: \n", Vt)

U: 
 [[-0.47185793 -0.8816746 ]
 [-0.8816746   0.47185793]]
Singular Values: 
 [4.6708301  0.42818941]
V Transpose: 
 [[-0.28978415 -0.95709203]
 [-0.95709203  0.28978415]]


**Exercise 1 :- Calculate Determinant and Inverse of a Matrix**

In [ ]:
import numpy as np
A = np.array([[2, 3, 4], [4, 5, 6], [7, 8, 9]])
determinant = np.linalg.det(A)
print("Determinant: \n", determinant)
# Check if the determinant is close to zero
if np.isclose(determinant, 0):
    print("Error: \n The matrix is singular (determinant is zero), so its inverse cannot be computed.")
else:
    inverse = np.linalg.inv(A)
    print("Inverse: \n", inverse)

Determinant: 
 0.0
Error: 
 The matrix is singular (determinant is zero), so its inverse cannot be computed.


**Exercise 2 :- Compute Eigenvalues and Eigenvectors adn perform SVD**

In [ ]:
import numpy as np
A = np.array([[3, 1, 1], [-1, 3, 1], [1, 1, 3]])
U, S, Vt = np.linalg.svd(A)
print("U: \n", U)
print("Singular Values: \n", S)
print("V Transpose: \n", Vt)
# Reconstruct
Sigma = np.zeros((3, 3))
np.fill_diagonal(Sigma, S)
reconstructed = U @ Sigma @ Vt
print("Reconstructed: \n", reconstructed)


U: 
 [[-0.57735027  0.57735027 -0.57735027]
 [-0.4412247  -0.81558342 -0.37435872]
 [-0.68701342  0.03860509  0.7256185 ]]
Singular Values: 
 [4.48261292 3.17102979 1.68841687]
V Transpose: 
 [[-0.4412247  -0.57735027 -0.68701342]
 [ 0.81558342 -0.57735027 -0.03860509]
 [-0.37435872 -0.57735027  0.7256185 ]]
Reconstructed: 
 [[ 3.  1.  1.]
 [-1.  3.  1.]
 [ 1.  1.  3.]]


**Additional Practice:**
> 1.Compute Eigenvalues and Eigenvectors for Larger Datasets

In [ ]:
import numpy as np
# large random matrix (1000×1000)
A = np.random.rand(1000, 1000)
# Compute eigenvalues & eigenvectors
vals, vecs = np.linalg.eig(A)
print("Eigenvalues shape: \n", vals.shape)
print("Eigenvectors shape: \n", vecs.shape)

Eigenvalues shape: 
 (1000,)
Eigenvectors shape: 
 (1000, 1000)


> 2. Use SVD to reduce the dimensionality of a Dataset

In [ ]:
import numpy as np
# Example dataset: m samples × n features
X = np.random.rand(1000, 50)   # 1000 samples, 50 features
# Step 1: Compute SVD
U, S, Vt = np.linalg.svd(X, full_matrices=False)
# Step 2: Choose k (reduced dimensions)
k = 10   # reduce from 50 → 10 dimensions
# Step 3: Reduce the dataset
X_reduced = U[:, :k] @ np.diag(S[:k])
print("Original shape: \n", X.shape)
print("Reduced shape: \n", X_reduced.shape)

Original shape: 
 (1000, 50)
Reduced shape: 
 (1000, 10)


> 3. Verify the property of Eigenvalues: det(A - $\lambda$ I) = 0

In [ ]:
import numpy as np
# Example matrix
A = np.array([[4, 2], [1, 3]])
# Step 1: Compute eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues: \n", eigenvalues)
# Step 2: Verify det(A - λI) = 0 for each eigenvalue
for lam in eigenvalues:
    left_matrix = A - lam * np.eye(A.shape[0])
    det_value = np.linalg.det(left_matrix)
    print(f"det(A - λI) for λ = {lam:.4f} → {det_value:.6f}")


Eigenvalues: 
 [5. 2.]
det(A - λI) for λ = 5.0000 → 0.000000
det(A - λI) for λ = 2.0000 → 0.000000
