<a href="https://colab.research.google.com/github/Jhansipothabattula/Machine_Learning/blob/main/Day115.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Constants, Variables and Placeholders

In [4]:
import tensorflow as tf

## Cnstants

# Create a constant tensor
constant_tensor = tf.constant([1, 2, 3, 4, 5])

print("Constant Tensor: \n", constant_tensor)

## Variables

# Create a variable tensor with initial values
initial_values = tf.random.normal(shape=(3, 3))
variable_tensor = tf.Variable(initial_values)

print("Variable tensor: \n", variable_tensor)

# Update variable tensor
new_values = tf.random.normal(shape=(3, 3))
variable_tensor.assign(new_values)

print("Updated variable tensor: \n", variable_tensor)

## TensorFlow 2.x Approach

# TensorFlow 2.x approach
x = tf.constant([[1.0, 2.0, 3.0,], [4.0, 5.0, 6.0]])

print(x)

# Direct computation without placeholders
y = tf.square(x)

print(y)

Constant Tensor: 
 tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Variable tensor: 
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-1.479272  , -1.05535   ,  0.03618637],
       [-0.82575643, -1.1015329 , -0.03127663],
       [-0.31606817, -1.6631627 ,  0.7073712 ]], dtype=float32)>
Updated variable tensor: 
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.13035488, -0.8309468 , -0.7236343 ],
       [-0.24188647,  0.18899505,  0.73742455],
       [-0.71270734, -0.1760225 ,  1.3159122 ]], dtype=float32)>
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
