<a href="https://colab.research.google.com/github/Jhansipothabattula/Machine_Learning/blob/main/Day114.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Operations

**Arithmetic Operations**


In [11]:
import tensorflow as tf

# Create Tensors
tensor_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32) # Changed to float32

# Addition
add_result = tf.add(tensor_a, tensor_b)

# Subtraction
sub_result = tf.subtract(tensor_a, tensor_b)

# Multiplication
mul_result = tf.multiply(tensor_a, tensor_b)

# Division
div_result = tf.divide(tensor_a, tensor_b)

print("Tensor A: \n", tensor_a)
print("Tensor B: \n", tensor_b)
print("Addition Result: \n", add_result)
print("Subtraction Result: \n", sub_result)
print("Multiplication Result: \n", mul_result)
print("Division Result: \n", div_result)

## Mathematical functions

# Square
square_result = tf.square(tensor_a)

# Square Root
sqrt_result = tf.sqrt(tensor_a)

# Exponential
exp_result = tf.exp(tensor_a)

# Logaritm
log_result = tf.math.log(tensor_a)

print("Square Result: \n", square_result)
print("Square Root Result: \n", sqrt_result)
print("Exponential Result: \n", exp_result)
print("Logarithmic Result: \n", log_result)

## Reduction Operations

# Sum along axis
result_sum = tf.reduce_sum(tensor_a, axis=0)

# Mean along axis
result_mean = tf.reduce_mean(tensor_a)

# Maximum value
result_max = tf.reduce_max(tensor_a)

# Minimum value
result_min = tf.reduce_min(tensor_a)

print("Sum Result: \n", result_sum)
print("Mean Result: \n", result_mean)
print("Maximum Result: \n", result_max)
print("Minimum Result: \n", result_min)

## Matrix Operations

# Matrix Multiplication
result_matmul = tf.matmul(tensor_a, tensor_b)

# Matrix Transportation
result_transpose = tf.transpose(tensor_a)

# Matrix Inverse(Requires TensorFlow Addons)
result_inverse = tf.linalg.inv(tensor_a)

print("Matrix Multiplication Result: \n", result_matmul)
print("Matrix Transpose Result: \n", result_transpose)
print("Inverse Result: \n", result_inverse)

## Indexing and Slicing

# Accessing Specific element

element = tensor_a[0, 0]

# Slicing
slice_tensor = tensor_a[:, 1]

print("Specific Element: \n", element)
print("Sliced Tensor: \n", slice_tensor)

## Broadcasting

# Broadcasting in arithemetic operations
tensor_c = tf.constant([1, 2], dtype=tf.float32) # Added dtype=tf.float32
result_broadcast = tensor_a + tensor_c #  TensorFLow is broadcasted to match the shape of tensor_a

print("Tensor: \n", tensor_c)
print("Broadcasted Result: \n", result_broadcast)

Tensor A: 
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Tensor B: 
 tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)
Addition Result: 
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Subtraction Result: 
 tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
Multiplication Result: 
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Division Result: 
 tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)
Square Result: 
 tf.Tensor(
[[ 1.  4.]
 [ 9. 16.]], shape=(2, 2), dtype=float32)
Square Root Result: 
 tf.Tensor(
[[1.        1.4142135]
 [1.7320508 2.       ]], shape=(2, 2), dtype=float32)
Exponential Result: 
 tf.Tensor(
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]], shape=(2, 2), dtype=float32)
Logarithmic Result: 
 tf.Tensor(
[[0.        0.6931472]
 [1.0986123 1.3862944]], shape=(2, 2), dtype=float32)
Sum Result: 
 tf.Tensor([4. 6.], shape=(2,), dtype=float32)
Mean Result: