<a href="https://colab.research.google.com/github/Jhansipothabattula/Linear_Regression/blob/main/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [46]:
#Array creation
arr = np.array([1, 2, 3, 4, 5])
print("Array: \n", arr)
#Zeroes array creation
zeroes = np.array((3, 3))
print("Zeroes array: \n", zeroes)
#Ones array creation
ones = np.ones((2, 4))
print("Ones array: \n", ones)
#Range of an array
range_array = np.arange(1, 100, 3)
print("Array range \n", range_array)
#Linspace of an array
linspace_array = np.linspace(0, 10, 5)
print("Linpace array: \n", linspace_array)
#Reshape of an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaped = arr.reshape(3, 3)
print("Reshaped array: \n", reshaped)
#Expansion of an array
arr = np.array([1, 2, 3])
expanded = arr[:, np.newaxis]
print("Expansion array: \n", expanded)

Array: 
 [1 2 3 4 5]
Zeroes array: 
 [3 3]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array range 
 [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
Linpace array: 
 [ 0.   2.5  5.   7.5 10. ]
Reshaped array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Expansion array: 
 [[1]
 [2]
 [3]]


In [48]:
#Array operations
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 1])
print("Addition: \n", A + B)
print("Multiplication: \n",A * B)
print("Subtraction: \n",A - B)
print("Division: \n",A / B)
#Array operations using range
A = np.arange(1, 5)
B = np.arange(6, 10)
print("Addition: \n",A + B)
print("Multiplication: \n",A * B)
print("Subtraction: \n",A - B)
print("Division: \n",A / B)

Addition: 
 [ 7  9 11 13  6]
Multiplication: 
 [ 6 14 24 36  5]
Subtraction: 
 [-5 -5 -5 -5  4]
Division: 
 [0.16666667 0.28571429 0.375      0.44444444 5.        ]
Addition: 
 [ 7  9 11 13]
Multiplication: 
 [ 6 14 24 36]
Subtraction: 
 [-5 -5 -5 -5]
Division: 
 [0.16666667 0.28571429 0.375      0.44444444]


In [49]:
#Array details
Arr = np.array([1, 2, 3, 4, 5])
print(np.sort(Arr))
print(np.sum(Arr))
print(np.mean(Arr))
print(np.max(Arr))
print(np.min(Arr))
#Array Slicing and Indexing
Arr = np.array([10, 20, 30, 40, 50])
print(arr[2])
print(arr[-1])
print(arr[1:4])
print(arr[3:])

[1 2 3 4 5]
15
3.0
5
1
3
3
[2 3]
[]


In [53]:
#Matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original matrix: \n", matrix)
#Transpose
transpose = matrix.T
print("Transpose matrix: \n", transpose)
#matrix sum
another_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix + another_matrix)
print("Matrix: \n", matrix)
print("Another matrix: \n", another_matrix)

Original matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Another matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
#Array and scalar broadcasting
arr = np.array([1, 2, 3])
print(arr + 10)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, 1])
print(matrix + vector)

[11 12 13]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


In [26]:
#Aggregation Functions: They compute summary statistics for array
#Common Functions
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Variance:", np.var(arr))
print("Standard Deviation:", np.std(arr))
print("Product:", np.prod(arr))
print("Cumulative Sum:", np.cumsum(arr))
print("Cumulative Product:", np.cumprod(arr))
print("Median:", np.median(arr))
print("Correlation Coefficient:", np.corrcoef(arr))
print("Unique Values:", np.unique(arr))
print("Percentiles:", np.percentile(arr, 50))
print("Cross Product:", np.cross(arr, arr))
print("Inner Product:", np.inner(arr, arr))
print("Outer Product:", np.outer(arr, arr))
print("Element-wise Product:", np.multiply(arr, arr))
print("Element-wise Division:", np.divide(arr, arr))
print("Element-wise Modulus:", np.mod(arr, arr))
print("Element-wise Exponentiation:", np.power(arr, arr))
print("Element-wise Square Root:", np.sqrt(arr))
print("Element-wise Square:", np.square(arr))
print("Element-wise Logarithm:", np.log(arr))
print("Element-wise Exponential:", np.exp(arr))
print("Element-wise Sine:", np.sin(arr))
print("Element-wise Cosine:", np.cos(arr))
print("Element-wise Tangent:", np.tan(arr))
print("Element-wise Inverse Sine:", np.arcsin(arr))
print("Element-wise Inverse Cosine:", np.arccos(arr))
print("Element-wise Inverse Tangent:", np.arctan(arr))
print("Element-wise Absolute Value:", np.abs(arr))
print("Element-wise Sign:", np.sign(arr))
print("Element-wise Ceil:", np.ceil(arr))
print("Element-wise Floor:", np.floor(arr))
print("Sum along rows:", np.sum(arr, axis=0))
print("Sum along columns:", np.sum(arr, axis=1))

Sum: 21
Mean: 3.5
Max: 6
Min: 1
Variance: 2.9166666666666665
Standard Deviation: 1.707825127659933
Product: 720
Cumulative Sum: [ 1  3  6 10 15 21]
Cumulative Product: [  1   2   6  24 120 720]
Median: 3.5
Correlation Coefficient: [[1. 1.]
 [1. 1.]]
Unique Values: [1 2 3 4 5 6]
Percentiles: 3.5
Cross Product: [[0 0 0]
 [0 0 0]]
Inner Product: [[14 32]
 [32 77]]
Outer Product: [[ 1  2  3  4  5  6]
 [ 2  4  6  8 10 12]
 [ 3  6  9 12 15 18]
 [ 4  8 12 16 20 24]
 [ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]]
Element-wise Product: [[ 1  4  9]
 [16 25 36]]
Element-wise Division: [[1. 1. 1.]
 [1. 1. 1.]]
Element-wise Modulus: [[0 0 0]
 [0 0 0]]
Element-wise Exponentiation: [[    1     4    27]
 [  256  3125 46656]]
Element-wise Square Root: [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Element-wise Square: [[ 1  4  9]
 [16 25 36]]
Element-wise Logarithm: [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
Element-wise Exponential: [[  2.71828183   7

/tmp/ipython-input-2845374802.py:31: RuntimeWarning: invalid value encountered in arcsin
  print("Element-wise Inverse Sine:", np.arcsin(arr))
/tmp/ipython-input-2845374802.py:32: RuntimeWarning: invalid value encountered in arccos
  print("Element-wise Inverse Cosine:", np.arccos(arr))


In [27]:
#Make values zero
arr = np.array([1, 2, 3, 4, 5])
evens = arr[arr % 2 == 0]
print("Evens:",evens)
arr[arr > 3] = 0
print("Modified Array:", arr)

Evens: [2 4]
Modified Array: [1 2 3 0 0]


In [32]:
#Random number and random integers generation and setting seeds
random_array = np.random.rand(3, 3)
print("Random array: \n", random_array)
random_integers = np.random.randint(0, 10, size=(2, 3))
print("Random intgers: \n", random_integers)
np.random.seed(42)

Random array: 
 [[0.04443092 0.40955825 0.90161018]
 [0.40382325 0.59359749 0.27301445]
 [0.72853086 0.18610239 0.79709685]]
Random intgers: 
 [[1 8 3]
 [7 2 7]]


In [33]:
#Matrix operations
matrix = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, -1])
result_add = matrix + vector
print("Addition: \n", result_add)
result_mul = matrix * vector
print("multiplication: \n", result_mul)

Addition: 
 [[2 2 2]
 [5 5 5]
 [8 8 8]]
multiplication: 
 [[ 1  0 -3]
 [ 4  0 -6]
 [ 7  0 -9]]


In [35]:
#Generate random dataset
dataset = np.random.randint(1, 51, size=(5, 5))
print("Original Dataset: \n", dataset)
#Filter values > 25 and replace with 0
dataset[dataset > 25] = 0
print("Modified Dataset: \n", dataset)
#Calculate summary stats
print("Sum: \n", np.sum(dataset))
print("Mean: \n", np.mean(dataset))
print("Max: \n", np.max(dataset))

Original Dataset: 
 [[39 29 15 43  8]
 [21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]]
Modified Dataset: 
 [[ 0  0 15  0  8]
 [21  0 19 23 11]
 [11 24  0  0 24]
 [ 3 22  2 24  0]
 [ 0  0  2 21  0]]
Sum: 
 230
Mean: 
 9.2
Max: 
 24


In [37]:
#Pandas
import pandas as pd
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print("s: \n",s)
data = {"Name":["Janu", "Indu", "prassu", "sharu", "varsha", "prami", "siri", "shafi"], "Age":[19, 19, 19, 19, 19, 19, 19, 19]}
df = pd.DataFrame(data)
print("DataFrame: \n", df)


s: 
 a    10
b    20
c    30
dtype: int64
DataFrame: 
      Name  Age
0    Janu   19
1    Indu   19
2  prassu   19
3   sharu   19
4  varsha   19
5   prami   19
6    siri   19
7   shafi   19


In [39]:
#Loading datasets from csv, excel, dictionary and other sources
df = pd.read_csv("data.csv")
df = pd.read_excel("data.excel")
#Save datasets to csv, excel
df.to_csv("data.csv")
df.to_excel("data.xlsx")
#Viewing data
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())
#Selecting and Indexing
print(df[["Name", "Age"]])
print(df[df["Age"] > 25])
#Selecting by position
print(df.loc[0])
print(df.iloc[:, 0])
#Selecting by label
print(df.loc[0, "Name"])

In [40]:
#Loading a real dataset
#https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv
import pandas as pd
df = pd.read_csv("#https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
print(df.info())
print(df.describe())
print(df.head())
print(df.tail())
selected_columns = df[["species", "sepal_length"]]
print("Selected columns: \n", selected_columns)
filtered_rows = df[(df["sepal_length"] > 5.0) & (df["species"] == "setosa")]
print("Filtered rows: \n", filtered_rows)