<a href="https://colab.research.google.com/github/Jhansipothabattula/Machine_Learning/blob/main/Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear ALgebra Fundamentals

**Vectors and Matrices**
1. Vector

   Example: [2, 3, 4]
2. Matrix
   Example:$$
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$$

**Matrix Operations**
1. Addition and Subtraction
2. Scalar Multiplication
3. Matrix Multiplication

In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Addition: \n", A + B)
print("Subtraction: \n", A - B)
C = 2 * A
print("Scalar Multiplication: \n", C)
result = np.dot(A, B)
print("Matrix Multiplication \n", result)

Addition: 
 [[ 6  8]
 [10 12]]
Subtraction: 
 [[-4 -4]
 [-4 -4]]
Scalar Multiplication: 
 [[2 4]
 [6 8]]
Matrix Multiplication 
 [[19 22]
 [43 50]]


**Scalar Matrices**
1. Identity Matrix(I)
   
   I . A = A
2. Zero Matrix(0)
3. Diagonal Matrix

In [ ]:
I = np.eye(5)
print("Identity Matrix: \n", I)
Z = np.zeros((2, 3))
print("Zero Matrix: \n", Z)
D = np.diag([1, 2, 3])
print("Diagonal Matrix: \n", D)

Identity Matrix: 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Zero Matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Diagonal Matrix: 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


**Exercise 1 :- Create Vectors and Matrices using Numpy**

In [ ]:
import numpy as np
# Create Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[9, 8], [7, 6]])
# Addition
print("Addition", A + B)
# Subtraction
print("Subtraction", A - B)
# Scalar Multiplication
print("Scalar Multiplication", 3 * A)

Addition [[10 10]
 [10 10]]
Subtraction [[-8 -6]
 [-4 -2]]
Scalar Multiplication [[ 3  6]
 [ 9 12]]


**Exercise 2 :- Implement Matrix-Vector Multiplication**

In [ ]:
import numpy as np
# Create Matrix and Vector
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([1, 0, -1])
# Matrix-Vector Multiplication
result = np.dot(M, v)
print("Matrix-Vector Multiplication \n", result)

Matrix-Vector Multiplication 
 [-2 -2 -2]


**Exercise 3 :- Explore Special Matrices**

In [ ]:
import numpy as np
# Identity Matrix
I = np.eye(3)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A X I: \n", np.dot(A, I))
# Diagonal and Zero Matrix
D = np.diag([1, 7, 9])
Z = np.zeros((3, 3))
print("Diagonal Matrix: \n", D)
print("Zero Matrix: \n", Z)

A X I: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Diagonal Matrix: 
 [[1 0 0]
 [0 7 0]
 [0 0 9]]
Zero Matrix: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Additional Practice:**

>1. Compute the determinant and inverse of a 2x2 matrix using numpy

In [2]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
det = np.linalg.det(A)
print("Determinant: \n", det)
inverse = np.linalg.inv(A)
print("Inverse: \n", inverse)

Determinant: 
 -2.0000000000000004
Inverse: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


>2. Verify properties of matrix multiplication

In [5]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])
C = np.array([[0, 1], [2, 3]])
left = A @ (B @ C)
right = (A @ B) @ C
print("Associative Property Verified:", np.allclose(left, right))
left = A @ (B + C)
right = (A @ B) + (A @ C)
print("Distributive Property Verified:", np.allclose(left, right))
I = np.eye(2)
print("Identity property: \n A * I == A:", np.allclose(A @ I, A))
print("Identity property: \n I * A == A:", np.allclose(I @ A, A))
print("Non commutative property: \n AB == BA:", np.allclose(A @ B, B @ A))
print("AB:\n", A @ B)
print("BA:\n", B @ A)

Associative Property Verified: True
Distributive Property Verified: True
Identity property: 
 A * I == A: True
Identity property: 
 I * A == A: True
Non commutative property: 
 AB == BA: False
AB:
 [[ 4  4]
 [10  8]]
BA:
 [[ 2  4]
 [ 7 10]]


>3. Create a block diagonal matrix uisng Numpy

In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
block_diag = np.block([[A, np.zeros((2,2))], [np.zeros((2,2)), B]
])
print(block_diag)

[[1. 2. 0. 0.]
 [3. 4. 0. 0.]
 [0. 0. 5. 6.]
 [0. 0. 7. 8.]]
